version: '3.1'
services:
  backend: 
    image: cities-backend
    ports:
    - '5000:5000'
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example_db
      JWT_KEY: my_super_secret_cat_key
  frontend: 
    image: cities-frontend
    ports:
    - '80:80'
    restart: always
    environment:
      VITE_API_URL: backend:5000
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example_db
    ports:
    - '3306:3306'
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'